#!/bin/bash
set -e
export RFSTOOLS_DEBUG=TRUE

die(){
  echo "$*"
  exit 1
}

generate_file()(
  tmp=$(mktemp)
  dd if=/dev/urandom of=$tmp bs=2048 count=65536
  echo $tmp
)

print_test_start(){
  printf "Starting test \e[1m$test\e[0m...\n"
}

print_test_fail(){
  printf "\e[31mTEST $test FAILED\e[0m \n\n"
  exit 1
}

print_test_succeeded(){
  printf "Test $test succeeded\n\n"
  test=NAN
}



