#!/bin/bash
set -e

if [ -z "$RFSTOOLS_DEBUG" ]; then
  export RFSTOOLS_DEBUG=TRUE
fi

die(){
  echo "$*"
  exit 1
}

generate_file()(
  tmp=$(mktemp)
  dd if=/dev/urandom of=$tmp bs=2048 count=65536
  echo $tmp
)

print_test_start(){
  printf "\nStarting test \e[1m$test\e[0m...\n"
}

print_test_fail(){
  printf "\e[31mTEST $test FAILED\e[0m \n"
  exit 1
}

print_test_succeeded(){
  printf "Test $test succeeded\n"
  test=NAN
}

run_test()(
 test=$1
 print_test_start

 $1 || print_test_fail  
 print_test_succeeded
  
)

